apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-certificates-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  node_cert.pem: {{ .Files.Get "secrets/node_cert.pem" | b64enc }}
  node_cert_key.pem: {{ .Files.Get "secrets/node_cert_key.pem" | b64enc }}
  admin_cert.pem: {{ .Files.Get "secrets/admin_cert.pem" | b64enc }}
  admin_cert_key.pem: {{ .Files.Get "secrets/admin_cert_key.pem" | b64enc }}
  ca_cert.pem: {{ .Files.Get "secrets/ca_cert.pem" | b64enc }}
  kibana_cookie_pwd: {{ .Files.Get "secrets/kibana_cookie_pwd.txt" | b64enc }}